/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slf4j.bugsample;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        System.out.println("STARTED SUCCESFULLY");
        logger.info("INFO message with no lambdas");
        logger.atInfo().addArgument(() -> { return "MESSAGE FROM LAMBDA"; })
                .log("INFO message with a lambda function result = {}");
        methodWithLoggerCall();
        System.out.println("ENDED SUCCESFULLY");
    }

    private static String getMethodMessage() {
        return "METHOD MESSAGE";
    }

    private static void methodWithLoggerCall() {
        logger.atInfo().addArgument(App::getMethodMessage).log("INFO message with a method reference {}");
    }
}
